services:

    mado.query_builder_factory:
        class: Mado\QueryBundle\Queries\QueryBuilderFactory
        arguments:
            - "@doctrine.orm.entity_manager"

    mado.query-bundle.config.provider:
        class: Mado\QueryBundle\Services\ConfigProvider
        arguments:
            - "@request_stack"
            - "@security.token_storage"
            - "@doctrine.orm.entity_manager"
